apiVersion: apps/v1
kind: Deployment
metadata:
  name: clockwise-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clockwise-backend
  template:
    metadata:
      labels:
        app: clockwise-backend
    spec:
      containers:
        - name: backend
          image: your-backend-image
          env:
            - name: MONGO_URI
              value: mongodb://clockwise-mongo:27017/clockwisedb
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: clockwise-backend
spec:
  selector:
    app: clockwise-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
