apiVersion: apps/v1
kind: Deployment
metadata:
  name: clockwise-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clockwise-frontend
  template:
    metadata:
      labels:
        app: clockwise-frontend
    spec:
      containers:
        - name: frontend
          image: your-frontend-image
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: clockwise-frontend
spec:
  selector:
    app: clockwise-frontend
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
